### ISSUE TITLE
Question on App Setup URL

### ISSUE THREAD

**Issue by zifahm** [nestjs-shopify/example-nx-app#1]
What should we add in the App setup section as
App URL and Allowed redirection URL(s)?

I'm little stuck here.

**Comment by tolgap** [comment]
I suggest you use ngrok.io to receive a public URL. Ngrok has TLS enabled so you will have an HTTPS url for your app.

You can use the following setup

Window 1:
```console
ngrok http 8081
```

Window 2:
```console
npx nx run web:serve
```

Window 3:
```console
npx nx run api:serve
```

Make sure you fill in this Ngrok URL in the `.env` file under `HOST`, and in your Partners Dashboard for the Shopify app that you use.

I would want to avoid this issue becoming a tutorial on Shopify and Ngrok. So hopefully this can help you get underway.

**Comment by zifahm** [comment]
I think I made it work,
but I kept getting the `ModuleRef missing in ShopifyCoreModule error` (writing from memory),
thus I have reverted back to the old api.

The example app is working in my system, there seems to be no errors, but once I add it into my app, then the whole things crashes witht the error stated above.

**Comment by zifahm** [comment]
btw I was aksing what to add in the shopify partner dashboard as App URL and Allowed redirection URL(s) 😅. 
The installation instruction was clear in the readme, just the shopify partner dasbhaord part was missing.

I got it working by adding ngrok url as App URL and the allowed redirections as /offline and /offline/callback

**Comment by tolgap** [comment]
> but I kept getting the `ModuleRef missing in ShopifyCoreModule error` (writing from memory),

If that's the case then I do need to see some code before I can tell what's wrong.

Usually errors like this happen when there are multiple versions of NestJS package mixed in your `package.json`.

Can you share the repository here? If not, could you reproduce it in a different repo?

**Comment by zifahm** [comment]
Sure creating a codesandbox

**Comment by tolgap** [comment]
@zifahm Here's a codesandbox I created: https://codesandbox.io/s/sleepy-feather-y70vf8

I don't notice any errors when using the packages `core` and `auth`. Can you fork this codesandbox and tell me how to reproduce your error 👍 ?

**Comment by zifahm** [comment]
😅 Thats what I was trying to do, to recreate the error that day, spent like a good 4 hrs on it.

Looks like the comment you said must have been the culprit.
> Usually errors like this happen when there are multiple versions of NestJS package mixed in your package.json.

Right now, I'm still using the old api, probably will allocate time updating it again in 2 weeks or so, will surely post about it.
