### ISSUE TITLE
Next Link doesn't work

### ISSUE THREAD

**Issue by dominikx96** [nestjs-shopify/example-nx-app#3]
@tolgap 
I'm trying to navigate between the next pages using `next/link`, but I'm getting:

<img width="749" alt="Screenshot 2022-11-18 at 17 05 56" src="https://user-images.githubusercontent.com/16655908/202749057-3944ed63-d6cd-4b8b-aeff-ad921a206864.png">

I also see in the console:
<img width="434" alt="Screenshot 2022-11-18 at 17 07 24" src="https://user-images.githubusercontent.com/16655908/202749388-a204d677-68ce-4821-b7ef-093fd2564866.png">

**Comment by tolgap** [comment]
This error should not happen anymore. We check in `getInitialProps` whether we're server side or not 👍. Thanks for reporting it initially @dominikx96
