### ISSUE TITLE
Theme App Extension

### ISSUE THREAD

**Issue by dominikx96** [nestjs-shopify/example-nx-app#30]
Hi @tolgap 

I used this started (it's really good!), but I'm curious about the theme app extension. My app adds some elements to the theme, so following the newest Shopify requirements, I have to use an app extension to add some liquid and scripts.

How do you deal with app extension, nx monorepo and shopify cli? Do you have any tips?
Thanks!

**Comment by tolgap** [comment]
@dominikx96 I thought about this for a while. I don't think it's the point of this repository to decide on how do to Theme App Extensions 🙂.

You can make things as opinionated as you want using Nx. I would suggest you put your theme extension into it's own Nx app.

That way it is managed in `apps/my-theme-extension` and you can setup Shopify CLI to only manage the theme app extension inside that "placeholder" Nx app.

You could even add the correct build/test steps for Nx to use by using the correct commands in `apps/my-theme-extension/project.json`.
