### ISSUE TITLE
I want to switch from Express to Fastify

### ISSUE THREAD

**Issue by llong2195** [nestjs-shopify/example-nx-app#45]
Thank you for the great repo. I want to switch from Express to Fastify, please guide me.

I simply switched from Express to Fastify and encountered this error
`import { Request, Response } from 'express';`
->
`import { FastifyRequest as Request, FastifyReply as Response } from 'fastify';`
![image](https://user-images.githubusercontent.com/68091468/233000940-d316e7e1-32a1-440c-a8ef-0c180188cf3b.png)

**Comment by tolgap** [comment]
@llong2195 this is not yet supported for `@nestjs-shopify/auth`. Could you open the ticket here: https://github.com/nestjs-shopify/nestjs-shopify/issues?

**Comment by tolgap** [comment]
Superseded by https://github.com/nestjs-shopify/nestjs-shopify/issues/202

**Comment by llong2195** [comment]
@tolgap 
i I solved it
my code:
![image](https://github.com/nestjs-shopify/example-nx-app/assets/68091468/50fe58ab-3884-464c-abee-34ba6291ed79)

**Comment by llong2195** [comment]
@tolgap According to the benchmark, Fastify is significantly faster. It's worth giving it a try.
