### ISSUE TITLE
InvalidHmacError: Query does not contain an HMAC value

### ISSUE THREAD

**Issue by Nziranziza** [nestjs-shopify/example-nx-app#98]
I've been following this example while working with NestJS. Everything is working well except for registering the webhook and the final redirection to online authentication. Attached is a screenshot of the error. Any assistance would be greatly appreciated.
<img width="1201" alt="image" src="https://github.com/nestjs-shopify/example-nx-app/assets/37615728/d76f7ce1-c3b1-4d35-8443-e24014923913">

**Comment by tolgap** [comment]
The error is in your logs.

```
You cannot create a webhook subscription with the specified topic
```

And do you have your `HOST` environment value set to your `tunnelmole.net` proxy?

**Comment by Nziranziza** [comment]
@tolgap thanks for a very quick response, I actually was able to get this working, I had to uninstall the app and run the app again

**Comment by tolgap** [comment]
@Nziranziza nice! Glad you could get it to work 👍
